-- 005_vocab_seed.sql — roaster + country vocabulary extracted from the
-- product brief's docx lists (Climb-Again/mycoffee-private, brief/MyCoffee app.docx).
-- The document itself is never copied here (personal purchase history + a
-- profile-avatar screenshot) — only the extracted vocabulary values are, per
-- CLAUDE.md's public-repo rule. Structure lives in 004_vocab.sql.
--
-- Source lists appear in the docx twice (two Photos-album exports, B superseding
-- A — never summed, since A's counts are a strict subset of B's, not a sibling
-- distribution) and under two SWAPPED headings: 'Roasters Countries list' holds
-- origin countries (Ethiopia, Kenya, Colombia…); 'Origin Countries list' opens
-- with roaster countries (Belgium, Czech Republic, Netherlands…) before switching
-- mid-list to origins. Seeded here by actual semantics, not by heading text.
--
-- Canonical roaster/country chosen as the fuller/cleaner spelling; every other
-- spelling variant the two exports use is seeded as an alias resolving to it.
-- 'Colombia / Brazilia' and 'Blend' in the origin list are per-coffee dual-origin
-- / blend notes, not new countries — 'Blend' is already the pseudo-country row
-- from 004_vocab.sql; dual-origin coffees are modeled by coffees.origin_country_ids
-- later, not by a vocabulary row.
--
-- Two names that look alike but are NOT merged (verified against the source lists
-- and kept as separate roasters — the fuzzy-matcher's own negative test cases):
--   'Father's Coffee Roastery' / 'Father's' (one roaster) vs 'Father Carpenter' (a
--   different one); 'Kofio' vs 'Kolibri' (two different roasters, not a typo pair).
--
-- roaster_id/country_id are looked up by name within this migration so re-running
-- (ON CONFLICT DO NOTHING) is idempotent even though IDs are IDENTITY-generated.

INSERT INTO countries (name, iso2, is_origin, is_roaster, kind) VALUES
  ('Ethiopia', 'ET', true, false, 'country'),
  ('Kenya', 'KE', true, false, 'country'),
  ('Rwanda', 'RW', true, false, 'country'),
  ('Colombia', 'CO', true, false, 'country'),
  ('Brazil', 'BR', true, false, 'country'),
  ('Bolivia', 'BO', true, false, 'country'),
  ('Burundi', 'BI', true, false, 'country'),
  ('Costa Rica', 'CR', true, false, 'country'),
  ('Ecuador', 'EC', true, false, 'country'),
  ('El Salvador', 'SV', true, false, 'country'),
  ('Guatemala', 'GT', true, false, 'country'),
  ('Indonesia', 'ID', true, false, 'country'),
  ('Mexico', 'MX', true, false, 'country'),
  ('Nicaragua', 'NI', true, false, 'country'),
  ('Panama', 'PA', true, false, 'country'),
  ('Papua New Guinea', 'PG', true, false, 'country'),
  ('Peru', 'PE', true, false, 'country'),
  ('Tanzania', 'TZ', true, false, 'country'),
  ('Uganda', 'UG', true, false, 'country'),
  ('Venezuela', 'VE', true, false, 'country'),
  ('Vietnam', 'VN', true, false, 'country'),
  ('Yemen', 'YE', true, false, 'country'),
  ('China', 'CN', true, false, 'country'),
  ('Honduras', 'HN', true, false, 'country'),
  ('Thailand', 'TH', true, false, 'country'),
  ('Belgium', 'BE', false, true, 'country'),
  ('Czech Republic', 'CZ', false, true, 'country'),
  ('Denmark', 'DK', false, true, 'country'),
  ('France', 'FR', false, true, 'country'),
  ('Germany', 'DE', false, true, 'country'),
  ('Ireland', 'IE', false, true, 'country'),
  ('Canada', 'CA', false, true, 'country'),
  ('Latvia', 'LV', false, true, 'country'),
  ('Netherlands', 'NL', false, true, 'country'),
  ('Norway', 'NO', false, true, 'country'),
  ('Poland', 'PL', false, true, 'country'),
  ('Slovakia', 'SK', false, true, 'country'),
  ('Spain', 'ES', false, true, 'country'),
  ('United States', 'US', false, true, 'country'),
  ('United Kingdom', 'GB', false, true, 'country'),
  ('Romania', 'RO', false, true, 'country')
ON CONFLICT (name) DO NOTHING;

INSERT INTO country_aliases (country_id, alias, alias_norm)
SELECT c.id, v.alias, v.alias_norm FROM (VALUES
  ('Ethiopia', 'Ethiopia', 'ethiopia'),
  ('Ethiopia', 'Etiopia', 'etiopia'),
  ('Kenya', 'Kenya', 'kenya'),
  ('Rwanda', 'Rwanda', 'rwanda'),
  ('Colombia', 'Colombia', 'colombia'),
  ('Colombia', 'Columbia', 'columbia'),
  ('Brazil', 'Brazil', 'brazil'),
  ('Brazil', 'Brazilia', 'brazilia'),
  ('Bolivia', 'Bolivia', 'bolivia'),
  ('Burundi', 'Burundi', 'burundi'),
  ('Costa Rica', 'Costa Rica', 'costa rica'),
  ('Ecuador', 'Ecuador', 'ecuador'),
  ('El Salvador', 'El Salvador', 'el salvador'),
  ('Guatemala', 'Guatemala', 'guatemala'),
  ('Indonesia', 'Indonesia', 'indonesia'),
  ('Indonesia', 'Indonezia', 'indonezia'),
  ('Mexico', 'Mexico', 'mexico'),
  ('Mexico', 'Mexic', 'mexic'),
  ('Nicaragua', 'Nicaragua', 'nicaragua'),
  ('Nicaragua', 'NIcaragua', 'nicaragua'),
  ('Panama', 'Panama', 'panama'),
  ('Papua New Guinea', 'Papua New Guinea', 'papua new guinea'),
  ('Peru', 'Peru', 'peru'),
  ('Tanzania', 'Tanzania', 'tanzania'),
  ('Uganda', 'Uganda', 'uganda'),
  ('Venezuela', 'Venezuela', 'venezuela'),
  ('Vietnam', 'Vietnam', 'vietnam'),
  ('Yemen', 'Yemen', 'yemen'),
  ('China', 'China', 'china'),
  ('Honduras', 'Honduras', 'honduras'),
  ('Thailand', 'Thailand', 'thailand'),
  ('Thailand', 'Thailanda', 'thailanda'),
  ('Belgium', 'Belgium', 'belgium'),
  ('Czech Republic', 'Czech Republic', 'czech republic'),
  ('Denmark', 'Denmark', 'denmark'),
  ('France', 'France', 'france'),
  ('Germany', 'Germany', 'germany'),
  ('Ireland', 'Ireland', 'ireland'),
  ('Canada', 'Canada', 'canada'),
  ('Latvia', 'Latvia', 'latvia'),
  ('Netherlands', 'Netherlands', 'netherlands'),
  ('Norway', 'Norway', 'norway'),
  ('Poland', 'Poland', 'poland'),
  ('Slovakia', 'Slovakia', 'slovakia'),
  ('Spain', 'Spain', 'spain'),
  ('United States', 'United States', 'united states'),
  ('United Kingdom', 'United Kingdom', 'united kingdom'),
  ('Romania', 'Romania', 'romania')
) AS v(country_name, alias, alias_norm)
JOIN countries c ON c.name = v.country_name
ON CONFLICT (alias_norm) DO NOTHING;

INSERT INTO roasters (name, slug)
SELECT r.name, r.slug FROM (VALUES
  ('DAK Coffee Roasters', 'dak-coffee-roasters'),
  ('The naughty dog', 'the-naughty-dog'),
  ('The Coffee Collective', 'the-coffee-collective'),
  ('People Possession', 'people-possession'),
  ('Father''s Coffee Roastery', 'father-s-coffee-roastery'),
  ('Doubleshot', 'doubleshot'),
  ('Coffea Circulor', 'coffea-circulor'),
  ('BirdSong Coffee', 'birdsong-coffee'),
  ('Beansmith''s', 'beansmith-s'),
  ('Fiftybeans', 'fiftybeans'),
  ('Rocket Bean Roastery', 'rocket-bean-roastery'),
  ('Nordbeans', 'nordbeans'),
  ('Concept Coffee Roasters', 'concept-coffee-roasters'),
  ('The Barn', 'the-barn'),
  ('Coffeein', 'coffeein'),
  ('Candycane Coffee', 'candycane-coffee'),
  ('Manhattan Coffee Roasters', 'manhattan-coffee-roasters'),
  ('Nomad Coffee', 'nomad-coffee'),
  ('Dos Mundos', 'dos-mundos'),
  ('Rebelbean', 'rebelbean'),
  ('Tribes of Mokha Roastery', 'tribes-of-mokha-roastery'),
  ('Square Mile', 'square-mile'),
  ('Sprout Coffee Roasters', 'sprout-coffee-roasters'),
  ('Poppy Beans', 'poppy-beans'),
  ('HAYB Speciality Coffee', 'hayb-speciality-coffee'),
  ('Respekt Coffee', 'respekt-coffee'),
  ('Not Another Boring Roastery', 'not-another-boring-roastery'),
  ('Mia Coffee Roastery', 'mia-coffee-roastery'),
  ('BOO Modern Coffee', 'boo-modern-coffee'),
  ('Tao Coffee', 'tao-coffee'),
  ('Kofio', 'kofio'),
  ('Tanat Coffee', 'tanat-coffee'),
  ('Kaffa', 'kaffa'),
  ('Blind Monkey', 'blind-monkey'),
  ('Gust Specialty Coffee', 'gust-specialty-coffee'),
  ('Roastlab coffee roasters', 'roastlab-coffee-roasters'),
  ('Lot Roastery', 'lot-roastery'),
  ('Krok', 'krok'),
  ('Oh My Bean Roastery', 'oh-my-bean-roastery'),
  ('Kmen Coffee Roasters', 'kmen-coffee-roasters'),
  ('September Coffee', 'september-coffee'),
  ('Typika', 'typika'),
  ('Hydrangea Coffee Roasters', 'hydrangea-coffee-roasters'),
  ('Punkt. coffee', 'punkt-coffee'),
  ('Industra Coffee', 'industra-coffee'),
  ('Guido', 'guido'),
  ('Keen Coffee', 'keen-coffee'),
  ('Maggma Beans', 'maggma-beans'),
  ('Man vs Machine', 'man-vs-machine'),
  ('Momos Coffee', 'momos-coffee'),
  ('Radical Coffee', 'radical-coffee'),
  ('Right Side', 'right-side'),
  ('Siemasu', 'siemasu'),
  ('A.M.O.C', 'a-m-o-c'),
  ('Ahiya Roasters', 'ahiya-roasters'),
  ('Aliena', 'aliena'),
  ('April', 'april'),
  ('Bani Beans', 'bani-beans'),
  ('Bonanza', 'bonanza'),
  ('Brewing Dealers', 'brewing-dealers'),
  ('Drop Coffee Roaster', 'drop-coffee-roaster'),
  ('Elbgold', 'elbgold'),
  ('Father Carpenter', 'father-carpenter'),
  ('Fjord', 'fjord'),
  ('Friedhats', 'friedhats'),
  ('FRUKT', 'frukt'),
  ('Gardelli', 'gardelli'),
  ('Goat Story', 'goat-story'),
  ('Goriffee', 'goriffee'),
  ('GroundState', 'groundstate'),
  ('Jonas Reindl', 'jonas-reindl'),
  ('Kawa', 'kawa'),
  ('Kolibri', 'kolibri'),
  ('La Cabra', 'la-cabra'),
  ('Legendary Everyday', 'legendary-everyday'),
  ('Mabo', 'mabo'),
  ('Nero Scuro', 'nero-scuro'),
  ('Nowhere', 'nowhere'),
  ('ONYX', 'onyx'),
  ('Process Coffee', 'process-coffee'),
  ('Roastery 29', 'roastery-29'),
  ('Rumbaba', 'rumbaba'),
  ('RushRush', 'rushrush'),
  ('Sloane', 'sloane'),
  ('Sumo Coffee Roasters', 'sumo-coffee-roasters'),
  ('Swerl', 'swerl'),
  ('Three Marks Coffee', 'three-marks-coffee'),
  ('Tim Wendelboe', 'tim-wendelboe'),
  ('Uncommon', 'uncommon')
) AS r(name, slug)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO roaster_aliases (roaster_id, alias, alias_norm)
SELECT r.id, v.alias, v.alias_norm FROM (VALUES
  ('DAK Coffee Roasters', 'DAK Coffee Roasters', 'dak coffee roasters'),
  ('DAK Coffee Roasters', 'DAK', 'dak'),
  ('The naughty dog', 'The naughty dog', 'the naughty dog'),
  ('The Coffee Collective', 'The Coffee Collective', 'the coffee collective'),
  ('People Possession', 'People Possession', 'people possession'),
  ('Father''s Coffee Roastery', 'Father''s Coffee Roastery', 'father''s coffee roastery'),
  ('Father''s Coffee Roastery', 'Father''s', 'father''s'),
  ('Doubleshot', 'Doubleshot', 'doubleshot'),
  ('Coffea Circulor', 'Coffea Circulor', 'coffea circulor'),
  ('BirdSong Coffee', 'BirdSong Coffee', 'birdsong coffee'),
  ('Beansmith''s', 'Beansmith''s', 'beansmith''s'),
  ('Beansmith''s', 'Beansmith.s', 'beansmith.s'),
  ('Fiftybeans', 'Fiftybeans', 'fiftybeans'),
  ('Rocket Bean Roastery', 'Rocket Bean Roastery', 'rocket bean roastery'),
  ('Nordbeans', 'Nordbeans', 'nordbeans'),
  ('Concept Coffee Roasters', 'Concept Coffee Roasters', 'concept coffee roasters'),
  ('The Barn', 'The Barn', 'the barn'),
  ('Coffeein', 'Coffeein', 'coffeein'),
  ('Candycane Coffee', 'Candycane Coffee', 'candycane coffee'),
  ('Candycane Coffee', 'CandyCane', 'candycane'),
  ('Manhattan Coffee Roasters', 'Manhattan Coffee Roasters', 'manhattan coffee roasters'),
  ('Manhattan Coffee Roasters', 'Manhattan', 'manhattan'),
  ('Nomad Coffee', 'Nomad Coffee', 'nomad coffee'),
  ('Nomad Coffee', 'NOMAD', 'nomad'),
  ('Dos Mundos', 'Dos Mundos', 'dos mundos'),
  ('Rebelbean', 'Rebelbean', 'rebelbean'),
  ('Tribes of Mokha Roastery', 'Tribes of Mokha Roastery', 'tribes of mokha roastery'),
  ('Square Mile', 'Square Mile', 'square mile'),
  ('Sprout Coffee Roasters', 'Sprout Coffee Roasters', 'sprout coffee roasters'),
  ('Sprout Coffee Roasters', 'Sprout Coffee Roaster', 'sprout coffee roaster'),
  ('Poppy Beans', 'Poppy Beans', 'poppy beans'),
  ('HAYB Speciality Coffee', 'HAYB Speciality Coffee', 'hayb speciality coffee'),
  ('Respekt Coffee', 'Respekt Coffee', 'respekt coffee'),
  ('Not Another Boring Roastery', 'Not Another Boring Roastery', 'not another boring roastery'),
  ('Mia Coffee Roastery', 'Mia Coffee Roastery', 'mia coffee roastery'),
  ('BOO Modern Coffee', 'BOO Modern Coffee', 'boo modern coffee'),
  ('BOO Modern Coffee', 'Boo!', 'boo!'),
  ('Tao Coffee', 'Tao Coffee', 'tao coffee'),
  ('Kofio', 'Kofio', 'kofio'),
  ('Tanat Coffee', 'Tanat Coffee', 'tanat coffee'),
  ('Tanat Coffee', 'Tanat', 'tanat'),
  ('Kaffa', 'Kaffa', 'kaffa'),
  ('Blind Monkey', 'Blind Monkey', 'blind monkey'),
  ('Gust Specialty Coffee', 'Gust Specialty Coffee', 'gust specialty coffee'),
  ('Gust Specialty Coffee', 'Gust. Specialty Coffee', 'gust. specialty coffee'),
  ('Gust Specialty Coffee', 'Gust Coffee', 'gust coffee'),
  ('Roastlab coffee roasters', 'Roastlab coffee roasters', 'roastlab coffee roasters'),
  ('Lot Roastery', 'Lot Roastery', 'lot roastery'),
  ('Krok', 'Krok', 'krok'),
  ('Oh My Bean Roastery', 'Oh My Bean Roastery', 'oh my bean roastery'),
  ('Kmen Coffee Roasters', 'Kmen Coffee Roasters', 'kmen coffee roasters'),
  ('September Coffee', 'September Coffee', 'september coffee'),
  ('Typika', 'Typika', 'typika'),
  ('Hydrangea Coffee Roasters', 'Hydrangea Coffee Roasters', 'hydrangea coffee roasters'),
  ('Punkt. coffee', 'Punkt. coffee', 'punkt. coffee'),
  ('Industra Coffee', 'Industra Coffee', 'industra coffee'),
  ('Guido', 'Guido', 'guido'),
  ('Keen Coffee', 'Keen Coffee', 'keen coffee'),
  ('Maggma Beans', 'Maggma Beans', 'maggma beans'),
  ('Man vs Machine', 'Man vs Machine', 'man vs machine'),
  ('Momos Coffee', 'Momos Coffee', 'momos coffee'),
  ('Radical Coffee', 'Radical Coffee', 'radical coffee'),
  ('Right Side', 'Right Side', 'right side'),
  ('Right Side', 'RightSide', 'rightside'),
  ('Siemasu', 'Siemasu', 'siemasu'),
  ('A.M.O.C', 'A.M.O.C', 'a.m.o.c'),
  ('Ahiya Roasters', 'Ahiya Roasters', 'ahiya roasters'),
  ('Aliena', 'Aliena', 'aliena'),
  ('April', 'April', 'april'),
  ('Bani Beans', 'Bani Beans', 'bani beans'),
  ('Bonanza', 'Bonanza', 'bonanza'),
  ('Brewing Dealers', 'Brewing Dealers', 'brewing dealers'),
  ('Drop Coffee Roaster', 'Drop Coffee Roaster', 'drop coffee roaster'),
  ('Elbgold', 'Elbgold', 'elbgold'),
  ('Father Carpenter', 'Father Carpenter', 'father carpenter'),
  ('Fjord', 'Fjord', 'fjord'),
  ('Friedhats', 'Friedhats', 'friedhats'),
  ('FRUKT', 'FRUKT', 'frukt'),
  ('Gardelli', 'Gardelli', 'gardelli'),
  ('Goat Story', 'Goat Story', 'goat story'),
  ('Goriffee', 'Goriffee', 'goriffee'),
  ('GroundState', 'GroundState', 'groundstate'),
  ('Jonas Reindl', 'Jonas Reindl', 'jonas reindl'),
  ('Kawa', 'Kawa', 'kawa'),
  ('Kolibri', 'Kolibri', 'kolibri'),
  ('La Cabra', 'La Cabra', 'la cabra'),
  ('Legendary Everyday', 'Legendary Everyday', 'legendary everyday'),
  ('Mabo', 'Mabo', 'mabo'),
  ('Nero Scuro', 'Nero Scuro', 'nero scuro'),
  ('Nowhere', 'Nowhere', 'nowhere'),
  ('ONYX', 'ONYX', 'onyx'),
  ('Process Coffee', 'Process Coffee', 'process coffee'),
  ('Roastery 29', 'Roastery 29', 'roastery 29'),
  ('Rumbaba', 'Rumbaba', 'rumbaba'),
  ('RushRush', 'RushRush', 'rushrush'),
  ('Sloane', 'Sloane', 'sloane'),
  ('Sumo Coffee Roasters', 'Sumo Coffee Roasters', 'sumo coffee roasters'),
  ('Swerl', 'Swerl', 'swerl'),
  ('Three Marks Coffee', 'Three Marks Coffee', 'three marks coffee'),
  ('Tim Wendelboe', 'Tim Wendelboe', 'tim wendelboe'),
  ('Uncommon', 'Uncommon', 'uncommon')
) AS v(roaster_name, alias, alias_norm)
JOIN roasters r ON r.name = v.roaster_name
ON CONFLICT (alias_norm) DO NOTHING;
