-- 034: wire logo_url for every roaster with a matching <slug>.webp file.
--
-- Root cause of "no roaster logo": (a) migrations 032/033 pointed onyx/origo/sumo/
-- watchhouse at .png/.jpeg which a later normalize sweep converted to .webp and
-- deleted (404), and (b) ~45 logo files were committed but never wired to logo_url.
-- This sets logo_url = the raw .webp URL for every roaster whose slug has a file.
-- Idempotent (IS DISTINCT FROM). Files verified present on main; slugs verified live.

UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/17g-coffee.webp' WHERE slug = '17g-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/17g-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/a-m-o-c.webp' WHERE slug = 'a-m-o-c' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/a-m-o-c.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/april.webp' WHERE slug = 'april' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/april.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/beberry-coffee.webp' WHERE slug = 'beberry-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/beberry-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/birdsong-coffee.webp' WHERE slug = 'birdsong-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/birdsong-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/boo-modern-coffee.webp' WHERE slug = 'boo-modern-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/boo-modern-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/brewing-dealers.webp' WHERE slug = 'brewing-dealers' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/brewing-dealers.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/coffea-circulor.webp' WHERE slug = 'coffea-circulor' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/coffea-circulor.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/coffeein.webp' WHERE slug = 'coffeein' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/coffeein.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/concept-coffee-roasters.webp' WHERE slug = 'concept-coffee-roasters' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/concept-coffee-roasters.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/cupping-room.webp' WHERE slug = 'cupping-room' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/cupping-room.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/d-origen.webp' WHERE slug = 'd-origen' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/d-origen.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/dak-coffee-roasters.webp' WHERE slug = 'dak-coffee-roasters' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/dak-coffee-roasters.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/dos-mundos.webp' WHERE slug = 'dos-mundos' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/dos-mundos.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/drop-coffee-roaster.webp' WHERE slug = 'drop-coffee-roaster' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/drop-coffee-roaster.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/elbgold.webp' WHERE slug = 'elbgold' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/elbgold.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/father-s-coffee-roastery.webp' WHERE slug = 'father-s-coffee-roastery' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/father-s-coffee-roastery.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/felix-kaffee.webp' WHERE slug = 'felix-kaffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/felix-kaffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/friedhats.webp' WHERE slug = 'friedhats' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/friedhats.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/frukt.webp' WHERE slug = 'frukt' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/frukt.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/gardelli.webp' WHERE slug = 'gardelli' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/gardelli.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/goriffee.webp' WHERE slug = 'goriffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/goriffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/guido.webp' WHERE slug = 'guido' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/guido.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/hayb-speciality-coffee.webp' WHERE slug = 'hayb-speciality-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/hayb-speciality-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/jonas-reindl.webp' WHERE slug = 'jonas-reindl' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/jonas-reindl.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/kaffa.webp' WHERE slug = 'kaffa' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/kaffa.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/kawa.webp' WHERE slug = 'kawa' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/kawa.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/keen-coffee.webp' WHERE slug = 'keen-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/keen-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/koff-bun.webp' WHERE slug = 'koff-bun' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/koff-bun.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/kofi-microroastery.webp' WHERE slug = 'kofi-microroastery' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/kofi-microroastery.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/koppi.webp' WHERE slug = 'koppi' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/koppi.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/la-cabra.webp' WHERE slug = 'la-cabra' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/la-cabra.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/legendary-everyday.webp' WHERE slug = 'legendary-everyday' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/legendary-everyday.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/livingfoodlab.webp' WHERE slug = 'livingfoodlab' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/livingfoodlab.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/mabo.webp' WHERE slug = 'mabo' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/mabo.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/maggma-beans.webp' WHERE slug = 'maggma-beans' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/maggma-beans.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/man-vs-machine.webp' WHERE slug = 'man-vs-machine' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/man-vs-machine.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/manhattan-coffee-roasters.webp' WHERE slug = 'manhattan-coffee-roasters' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/manhattan-coffee-roasters.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/manufaktura.webp' WHERE slug = 'manufaktura' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/manufaktura.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/mere-black-coffee.webp' WHERE slug = 'mere-black-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/mere-black-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/mission-coffee-works.webp' WHERE slug = 'mission-coffee-works' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/mission-coffee-works.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/monmouth.webp' WHERE slug = 'monmouth' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/monmouth.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/nowhere.webp' WHERE slug = 'nowhere' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/nowhere.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/onyx.webp' WHERE slug = 'onyx' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/onyx.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/origo.webp' WHERE slug = 'origo' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/origo.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/people-possession.webp' WHERE slug = 'people-possession' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/people-possession.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/public-coffee-roasters.webp' WHERE slug = 'public-coffee-roasters' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/public-coffee-roasters.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/radical-coffee.webp' WHERE slug = 'radical-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/radical-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/right-side.webp' WHERE slug = 'right-side' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/right-side.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/root-branch.webp' WHERE slug = 'root-branch' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/root-branch.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/rumbaba.webp' WHERE slug = 'rumbaba' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/rumbaba.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/sentido.webp' WHERE slug = 'sentido' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/sentido.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/sloane.webp' WHERE slug = 'sloane' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/sloane.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/spojka.webp' WHERE slug = 'spojka' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/spojka.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/sprout-coffee-roasters.webp' WHERE slug = 'sprout-coffee-roasters' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/sprout-coffee-roasters.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/sumo-coffee-roasters.webp' WHERE slug = 'sumo-coffee-roasters' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/sumo-coffee-roasters.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/taf.webp' WHERE slug = 'taf' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/taf.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/tanat-coffee.webp' WHERE slug = 'tanat-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/tanat-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/the-barn.webp' WHERE slug = 'the-barn' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/the-barn.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/the-naughty-dog.webp' WHERE slug = 'the-naughty-dog' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/the-naughty-dog.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/three-marks-coffee.webp' WHERE slug = 'three-marks-coffee' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/three-marks-coffee.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/tim-wendelboe.webp' WHERE slug = 'tim-wendelboe' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/tim-wendelboe.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/uncommon.webp' WHERE slug = 'uncommon' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/uncommon.webp';
UPDATE roasters SET logo_url = 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/watchhouse.webp' WHERE slug = 'watchhouse' AND logo_url IS DISTINCT FROM 'https://raw.githubusercontent.com/Climb-Again/MyCoffee/main/ops/roaster-assets/logos/watchhouse.webp';
